modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "incurable"
version = "${version}"
displayName = "Incurable"
authors = "TeamPotato"
description = '''
这是一个非常简单的模组，添加了“禁疗”的药水效果，持有者将无法以任何形式恢复血量。
此效果目前只能通过/effect指令获得，若想在生存模式中正常使用，请整合包作者自行魔改。
'''

[[dependencies.incurable]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
